
# try except
# 程序一旦出现异样，不会报错 会给出异常提示
try:
    num = int(input("请输入整数"))

except:

    print('请输入整数')